apiVersion: apps/v1
kind: Deployment
metadata:
  name: sus-gopher-facts
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: sus-gopher-facts
  template:
    metadata:
      labels:
        app: sus-gopher-facts
    spec:
      containers:
      - image: diegoalveslv/sus-gopher-facts:latest
        name: sus-gopher-facts
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: sus-gopher-facts
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: sus-gopher-facts
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sus-gopher-facts
  labels:
    name: sus-gopher-facts
spec:
  rules:
  - host: "facts.127.0.0.1.nip.io"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: sus-gopher-facts
            port: 
              number: 80
